### ISSUE TITLE
 pea10059 doesn't appear in port nRF Connect serial port in osx mohave

### ISSUE THREAD

**Issue by mron** [NordicSemiconductor/pc-nrfconnect-ble#105]
This seems like an old issue without a clear solution. I have a 2012 MacBook pro running os x 10.14. I have a pca10059. nRF Connect v2.6.1 and JLinkExe v642b. The nRF Dongle will not show up in the port selection. The device is in /dev/tty.

This is likely a JLink problem.

**Comment by bihanssen** [comment]
Hi,
it's likely not a JLink problem as there is no JLink chip on the nRF52 Dongle.

Could you try to click the reset button and set it in bootloader mode manually (the tiny button facing away from the usb port). Observe it starts to blink red.

What is the port name in /dev/tty? tty.usbmodem...?

**Comment by mron** [comment]
Bjorn,

Thanks for your reply,

The tty port is  /dev/tty.usbmodemE96EA6C43AC62. I updated nRF Connect to v2.6.1 and I can see the now dongle. Here is the output after I connect to the device:

05:39:06.057	Application data folder: /Users/ron/Library/Application Support/nrfconnect/pc-nrfconnect-ble
05:39:12.437	Validating connectivity firmware for device with serial number E96EA6C43AC6...
05:39:32.681	Connectivity firmware is valid.
05:39:32.682	Connectivity firmware version: ble-connectivity 0.1.0+Aug-14-2018-15-12-51. SoftDevice API version: 3. Baud rate: 115200.
05:39:32.693	Opening adapter connected to /dev/tty.usbmodemE96EA6C43AC62
05:39:33.304	Successfully opened /dev/tty.usbmodemE96EA6C43AC62. Baud rate: 115200. Flow control: none. Parity: none.
05:39:33.305	Reset performed on adapter /dev/tty.usbmodemE96EA6C43AC62
05:39:33.873	Adapter connected to /dev/tty.usbmodemE96EA6C43AC62 opened

Programmed v1.02 also launches. The Dongle only blinks when the Programmer module of nRF Connect is open.

nrfjprog isn’t working as far as I can tell.

Ron

**Comment by bihanssen** [comment]
nrfjprog does not support the nRF52 Dongle because it has no JLink debugger chip onboard.

**Comment by mron** [comment]
Is that a command line programming option?

**Comment by mron** [comment]
Sorry,
I meant is there a command line programmer available?

**Comment by bihanssen** [comment]
For command line programming of nRF52 Dongle you can choose between:
[nrfutil](https://github.com/NordicSemiconductor/pc-nrfutil) and
[device-setup-js](https://github.com/NordicSemiconductor/nrf-device-setup-js)

Note that for nrfutil you will need enter bootloader mode manually until next release of nrfutil.

**Comment by mron** [comment]
Thanks,
I’ll check them out. Is there any on chip debugging available?

**Comment by bihanssen** [comment]
You can do chip debugging if you have an external debugger or if you connect the debug out connector from a Nordic development kit. Please check out [devzone](https://devzone.nordicsemi.com) for further info or questions regarding the nRF52 Dongle.
