### ISSUE TITLE
fatal: Unable to find remote helper for 'git+https' with npm

### ISSUE THREAD

**Issue by jetacpp** [NordicSemiconductor/pc-nrfconnect-ble#107]
Hello,
I tried to compile the project but it looked like there is some package issue with the repo:

> npm install 
npm WARN addRemoteGit Error: Command failed: git config --get remote.origin.url
npm WARN addRemoteGit 
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:275:12)
npm WARN addRemoteGit     at emitTwo (events.js:126:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:214:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:925:16)
npm WARN addRemoteGit     at Socket.stream.socket.on (internal/child_process.js:346:11)
npm WARN addRemoteGit     at emitOne (events.js:116:13)
npm WARN addRemoteGit     at Socket.emit (events.js:211:7)
npm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:567:12)
npm WARN addRemoteGit  git+https://github.com/NordicSemiconductor/pc-nrfconnect-devdep.git#semver:^1.3.2 resetting remote /home/dev/.npm/_git-remotes/git-https-github-com-NordicSemiconductor-pc-nrfconnect-devdep-git-semver-1-3-2-af3a631c because of error: { Error: Command failed: git config --get remote.origin.url
npm WARN addRemoteGit 
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:275:12)
npm WARN addRemoteGit     at emitTwo (events.js:126:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:214:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:925:16)
npm WARN addRemoteGit     at Socket.stream.socket.on (internal/child_process.js:346:11)
npm WARN addRemoteGit     at emitOne (events.js:116:13)
npm WARN addRemoteGit     at Socket.emit (events.js:211:7)
npm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:567:12)
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git config --get remote.origin.url' }
npm ERR! git clone --template=/home/dev/.npm/_git-remotes/_templates --mirror git+https://github.com/NordicSemiconductor/pc-nrfconnect-devdep.git /home/dev/.npm/_git-remotes/git-https-github-com-NordicSemiconductor-pc-nrfconnect-devdep-git-semver-1-3-2-af3a631c: Cloning into bare repository '/home/dev/.npm/_git-remotes/git-https-github-com-NordicSemiconductor-pc-nrfconnect-devdep-git-semver-1-3-2-af3a631c'...
npm ERR! git clone --template=/home/dev/.npm/_git-remotes/_templates --mirror git+https://github.com/NordicSemiconductor/pc-nrfconnect-devdep.git /home/dev/.npm/_git-remotes/git-https-github-com-NordicSemiconductor-pc-nrfconnect-devdep-git-semver-1-3-2-af3a631c: fatal: Unable to find remote helper for 'git+https'
npm ERR! Linux 4.15.0-43-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code 128

npm ERR! Command failed: git clone --template=/home/dev/.npm/_git-remotes/_templates --mirror git+https://github.com/NordicSemiconductor/pc-nrfconnect-devdep.git /home/dev/.npm/_git-remotes/git-https-github-com-NordicSemiconductor-pc-nrfconnect-devdep-git-semver-1-3-2-af3a631c
npm ERR! Cloning into bare repository '/home/dev/.npm/_git-remotes/git-https-github-com-NordicSemiconductor-pc-nrfconnect-devdep-git-semver-1-3-2-af3a631c'...
npm ERR! fatal: Unable to find remote helper for 'git+https'
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/dev/Projects/nordic/pc-nrfconnect-ble/npm-debug.log

**Comment by bencefr** [comment]
Hi @jetacpp , npm version 3.5.2 looks suspiciously very old, please try to update your npm (nodejs).

**Comment by jetacpp** [comment]
With this command, I resolved the issue
`git config --global url."https://".insteadOf git+https://`
