### ISSUE TITLE
[object Object] in DFU Package info

### ISSUE THREAD

**Issue by coderbyheart** [NordicSemiconductor/pc-nrfconnect-ble#180]
After selecting a ZIP file, the `info_read_only_metadata` is not properly printed:

![image](https://user-images.githubusercontent.com/188915/100253404-5cb9eb00-2f41-11eb-928a-ed2df06a805c.png)

Version: v3.6.0

**Comment by bihanssen** [comment]
Thanks for reporting, Markus. 
Ticket created, NCP-3423.
