### ISSUE TITLE
v3.0.0 no longer closes device on lost connection 

### ISSUE THREAD

**Issue by GrantRolls** [NordicSemiconductor/pc-nrfconnect-ble#239]
After upgrading to v3.0.0 with the new UI, there are some changes that have caused persistent connections to become broken

1. If a connected (peripheral) device is powered down or connection is lost, the display no longer automatically closes the connected device. Cant manually disconnect device. Requires app restart to connect again
2. If the scanning (central) device is unplugged or connection lost, the UI and application hangs. Requires app restart to fix

point 1 was handy from a testing perspective to monitor bluetooth connection losses - especially for use with EMC testing

**Comment by datenreisender** [comment]
What kind of devices are you working with? One of ours with a JLink chip on it, your own board through a different JLink device (which one?), or something else?

**Comment by GrantRolls** [comment]
The central devices we are using are nRF52840 Dongles

**Comment by GrantRolls** [comment]
Windows 10 machine, up-to-date security and patches

**Comment by datenreisender** [comment]
Thanks for the information. I will try to reproduce it.
