### ISSUE TITLE
Filter options like nRF Connect for Mobile

### ISSUE THREAD

**Issue by epac-tom** [NordicSemiconductor/pc-nrfconnect-ble#247]
Any chance we can get the same filtering options in the desktop app that we get in the mobile app?
Specifically I'm interested in filtering by raw advertising data, but all the filters would be great.

**Comment by johnnylei520** [comment]
![image](https://user-images.githubusercontent.com/44088060/172552636-cd94d710-ff71-4f3f-bd9e-12e5340d88ed.png)
you can use address filter

**Comment by epac-tom** [comment]
@johnnylei520 yeah I'm aware of the address filter. As mentioned I'm specificallly interested in advertising data - so that I can filter by Company ID. This is so that I can find devices without needing to know the address beforehand.
All filters would be the best outcome as then it is consitent with the functionality available in the mobile apps.

**Comment by datenreisender** [comment]
Sorry, we won't add this to the desktop app in the foreseeable future.
