### ISSUE TITLE
Custom service is not displayed when Notification characteristic ist added

### ISSUE THREAD

**Issue by Kampi** [NordicSemiconductor/pc-nrfconnect-ble#279]
I´m using the BLE app (v4.0.4) for creating a simple testing server with one test service. This test service should contain three characteristic
- Write
- Read
- Notification

The service is displayed correctly in the `Connection Map` by using these settings for the `Notification Service`:

![image](https://github.com/NordicSemiconductor/pc-nrfconnect-ble/assets/3458587/229ad446-5ce3-46fb-a3df-8216fe46bd86)
![image](https://github.com/NordicSemiconductor/pc-nrfconnect-ble/assets/3458587/edb424e6-0010-4cc2-ae40-ffb2d114bf1f)

And it isn´t displayed when enabling `Notify`

![image](https://github.com/NordicSemiconductor/pc-nrfconnect-ble/assets/3458587/881799fa-e8ca-418a-b147-a023d1f0413a)
![image](https://github.com/NordicSemiconductor/pc-nrfconnect-ble/assets/3458587/b9049dd8-73a1-4506-9a1e-d868d066d3be)

I also get the following message

```
13:59:13.887	Failed to set services
13:59:13.887	Expected Array or iterable object of values: 0
13:59:21.513	Failed to set services
13:59:21.513	Error occurred adding characteristic.
```

Is this a bug or I´m using the app wrong?

**Comment by bihanssen** [comment]
Hi. When adding a notify property to the characteristic, the setup expects a CCCD descriptor to be present. The descriptor needs to be added manually, as a child of the characteristic. I suspect that is the problem here.

**Comment by Kampi** [comment]
Hi @bihanssen 

thanks. That solves the issue.
