### ISSUE TITLE
cannot begin scanning for ble devices

### ISSUE THREAD

**Issue by batosi175** [NordicSemiconductor/pc-nrfconnect-ble#53]
Currently on On a mac running nRF connect 2.0.0 BLE App and the start scanning is disabled. 
![image](https://user-images.githubusercontent.com/9507793/28029559-0dedcb0c-6566-11e7-8e93-690bd6cef571.png)

i've got a nordic board that i'm meant to interface with through the bluetooth module, but i'm not even seeing any bluetooth devices broadcasting.

if i try to get around the disabled button by hitting the alt+ s shortcut it returns an error in the log file: 

> No adapter selected or adapter is missing state. Failing.

**Comment by mrodem** [comment]
Judging by the screenshot and log it seems that you have not selected a serial port. You need to insert your devkit/dongle into a USB port, and then select it from the "Select serial port" dropdown menu. After doing this, you should be able to scan for devices.

**Comment by mooreaa** [comment]
I ran into this issue as well. Can the app not use the BLE built into the mac system?

**Comment by mrodem** [comment]
@mooreaa As stated in the documentation, the app is designed to be used together with the nRF52 DK, nRF51 DK, or the nRF51 Dongle. Other devices are not supported.

**Comment by JavierReyes945** [comment]
> As stated in the documentation, the app is designed to be used together with the nRF52 DK, nRF51 DK, or the nRF51 Dongle. Other devices are not supported.

Should be even clear from the very Install option in the nRF Connect for Desktop app, or event in [this](https://github.com/NordicSemiconductor/pc-nrfconnect-ble) documentation that is linked in the "More Info" button for the App

![image](https://github.com/NordicSemiconductor/pc-nrfconnect-ble/assets/17864163/ababdf3b-d59e-4693-b868-c76ef134f5ac)

Even the words "General tool for development" is not really met if only a few devices are supported. The wording implies that it would work with any nordic device (and it is kind of an expected requirement).
