### ISSUE TITLE
IDE for the project

### ISSUE THREAD

**Issue by Nppn7** [NordicSemiconductor/pc-nrfconnect-ble#55]
Hello,

I'm new to JS. What IDE can you recommend to work with this project, instead of the method with "npm install" via cmd?

Thanks.

**Comment by bencefr** [comment]
Hi,
If you intend to develop this app we recommend to use an editor that supports `eslint`. These days I use [atom](https://atom.io/), others prefer [visualstudio code](https://code.visualstudio.com/), kde's kate, sublime or webstorm must be good choices as well.

**Comment by Nppn7** [comment]
Hello bencefr,

thank you very much for your quick response.
