### ISSUE TITLE
Automation of Scanning, Connecting and Bonding to a Device

### ISSUE THREAD

**Issue by Nppn7** [NordicSemiconductor/pc-nrfconnect-ble#56]
Hello,

I would like to automate the process of scanning, connecting and bonding to a device.

1. What I would like to achive: After clicking "Start Scan" button, the app should scan for new devices. When it finds a certain device with a specific address, it should automatically connect and bond to it.

2. Where I'm currently stuck: In the file "discoverReducers.js" is a function called `deviceDiscovered(oldState, device)`. Here I added following lines:

`if (newDevice.address === '00:0B:57:15:8C:8F') {`
       `logger.info('Try stop scanning');`
       ` DiscoveryAction.stopScan(dispatch, getState);`
       `logger.info(`Try to connect automatically to ${newDevice.address}`);`
       `deviceConnect(state, newDevice);`
` }`

Filtering and writing to log work. But when I try to stop the scanning process, by using the function `stopScan(dispatch, getState)` from the file "discoveryActions.js" I need to pass the variables `dispatch` and `getState`. These variables are unknown and I don't understand why because in the file "discoveryActions.js" they are kind of used the same way while never being really _declared_. 

3. My question now is: How can I make the variables `dispatch` and `getState` be available in the file"discoverReducers.js"? Or is there any other way to achieve my goal?

Thanks.

**Comment by bencefr** [comment]
I would suggest to read [creating apps](https://github.com/NordicSemiconductor/pc-nrfconnect-core/wiki), to get familiar with our concepts first.

You could store dispatch/getState, however that breaks the structure and logic of your code.
You should 
1. use the *reducers* to build the required props of the components of the UI from the state off the app
2. not use the *reducers* to trigger actions, but you can create complex actions where dispatch/getState is already available

Figure out which *action* `deviceDiscovered()` is triggered from (e.g. `AdapterAction.DEVICE_DISCOVERED`) and rather make your modifications there. [hint](https://github.com/NordicSemiconductor/pc-nrfconnect-ble/blob/master/lib/actions/adapterActions.js#L448)

**Comment by chunfantasy** [comment]
@Nppn7 , @bencefr has anwsered your question.
Since I worked on it recently, I can suggest you a solution with more detail.

Before giving  you the suggestion, I need to mention several things about `store` in Redux. [http://redux.js.org/docs/basics/Store.html]
Think `store` as a fridge.

1. getState(). getState() shows everything you saved in your fridge, like 2 apples, 1 milk, 3 bananas, which is a `state`.
2. dispatch(action). dispatch(action) changes something you saved in your fridge, which updates a `state`. For example, I do an action of drinking milk, and the state becomes 2 apples, 0 milk, 3 bananas.
3. subscribe(listener). The `listener` monitors your `state`. You can set conditions in the listener and set actions which will be triggered according to the certain conditions which will lead to a new dispatch(action) and change the state. For example, when milk is 0, trigger an action of buying new one. After dispatch(buyMilkAction), the state becomes 2 apples, 1 milk, 3 bananas.

OK, what does `Reducer` do then?

`Reducer` is doing the job of changing state. Whenever there is a dispatch(action), it check what the current state is, how things should be changed in the state according to the action, and then change the state and return the new state.

So, `Reducer` does not trigger any new action. If you wanna do something based on the new changed state, use the `listener`.

To find out where `dispatch` is.

1. Find onScanClicked() used in lib/components/discoveryButton.jsx 
2. Find DiscoveryButton used in lib/components/DiscoveredDevices.jsx
3. Find DiscoveredDevices used in `decorateSidePanel` in index.jsx
4. In `mapSidePanelDispatch`, it passes the parameter `dispatch`.
Reference [site]

Now here comes the solution with the links bence mentioned above.


startScan(dispatch, getState); // in action

// Then do something in Reducer or you can choose to do nothing in Reducer

adapterToUse.on('deviceDiscovered', device => {
    handleDeviceEvent(device, dispatch, getState, () => { 
        if (device.address === '00:0B:57:15:8C:8F') {
			logger.info('Try stop scanning');
			DiscoveryAction.stopScan(dispatch, getState);
			logger.info(Try to connect automatically to ${newDevice.address});
			deviceConnect(state, newDevice);
		}
    });
});

I will modify something later.

**Comment by Nppn7** [comment]
Hello bencefr,

thanks for your answer. I followed your advice and moved my modifications to [adapterActions.js#L205](https://github.com/NordicSemiconductor/pc-nrfconnect-ble/blob/master/lib/actions/adapterActions.js#L205). Now it looks like this:

`function deviceDiscoveredAction(dispatch, getState, device) {`
   ` if (device.address === '00:0B:57:15:8C:8F') {`
     `   logger.info('Try to stop scanning');`
      `  DiscoveryAction.stopScan(dispatch, getState);`
      `  logger.info('Scanning stopped');`
  `  }`
 `   return {`
  `      type: DEVICE_DISCOVERED,`
  `      device,`
  `  };`
`}`

I pass the two newly needed variables `dispatch` and `getState` in [adapterActions.js#L450](https://github.com/NordicSemiconductor/pc-nrfconnect-ble/blob/master/lib/actions/adapterActions.js#L450). 

In [discoveryActions.js#L128](https://github.com/NordicSemiconductor/pc-nrfconnect-ble/blob/master/lib/actions/discoveryActions.js#L128) I added a line to check whether the function `stopScan(dispatch, getState)` is executed or not.

The problem now is that when I manually click the "Stop scan" button in the UI the function `stopScan(dispatch, getState)` is fired. But when the device with the specific address is discovered (the `if` statement is entered) the function `stopScan(dispatch, getState)` seems not to be fired.

What am I doing wrong?

**Comment by chunfantasy** [comment]
Hi, @Nppn7 

As I explained above, you should write `stopScan()` in the `listener` which is [here](https://github.com/NordicSemiconductor/pc-nrfconnect-ble/blob/master/lib/actions/adapterActions.js#L448).

Put your code here like this
```javascript
// Add listener to handle event
adapterToUse.on('deviceDiscovered', newDevice => {
    handleDeviceEvent(device, dispatch, getState, () => { 
        if (newDevice.address === '00:0B:57:15:8C:8F') {
			logger.info('Try stop scanning');
			DiscoveryAction.stopScan(dispatch, getState);
			logger.info(Try to connect automatically to ${newDevice.address});
			deviceConnect(state, newDevice);
		}
    });
});
```

**Comment by Nppn7** [comment]
Hi chunfantasy,

thanks for your reply. Following your suggestion I modified [adapterActions.js#L448](https://github.com/NordicSemiconductor/pc-nrfconnect-ble/blob/master/lib/actions/adapterActions.js#L448) as follows:

    adapterToUse.on('deviceDiscovered', device => {
        handleDeviceEvent(device, getState, () => {
            // dispatch(deviceDiscoveredAction(device));
            DiscoveryAction.stopScan(dispatch, getState);
        });
    });

I also tried:

    adapterToUse.on('deviceDiscovered', device => {
        handleDeviceEvent(device, dispatch, getState, () => {
            // dispatch(deviceDiscoveredAction(device));
            DiscoveryAction.stopScan(dispatch, getState);
        });
    });

Both resulting in not finding any devices after I click the button "Start Scan"

**Comment by chunfantasy** [comment]
Hi @Nppn7,

Add `export` in front of `function stopScan()` in discoveryActions.js#98.
Since it is an internal function, you need to export it if you need to use it somewhere else.

**Comment by Nppn7** [comment]
Hi chunfantasy,

`export` doesn't seem to influence the behavior. With and without `export`, `npm run dev` doesn't thow errors. Also during runtime no device is found.

**Comment by chunfantasy** [comment]
[adapterActions.js#L448](https://github.com/NordicSemiconductor/pc-nrfconnect-ble/blob/master/lib/actions/adapterActions.js#L448)
```javascript
adapterToUse.on('deviceDiscovered', device => {
    handleDeviceEvent(device, getState, () => {
        DiscoveryActions.stopScan(dispatch, getState);
        dispatch(deviceDiscoveredAction(device));
    });
});
```
[discoveryActions.js#L128](https://github.com/NordicSemiconductor/pc-nrfconnect-ble/blob/master/lib/actions/discoveryActions.js#L128)
```javascript
export function stopScan(dispatch, getState) {
    ...
}
```

These are the only two places I changed. 
It works fine with discovering one device and stop scanning, although there is another issue which is not relevant to this.

If it is still not working for you, can you see what happens in the console?

**Comment by Nppn7** [comment]
Hi @chunfantasy,

I made it work using your code. The issue that you mean is probably the following `Error occured when stopping scan. Errorcode: NRF_ERROR_INVALID_STATE (0x8)`:

<img width="947" alt="nrfc" src="https://user-images.githubusercontent.com/30924911/29398696-50403124-8326-11e7-8082-88d21523bd4e.png">

**Comment by chunfantasy** [comment]
@Nppn7 

Great! This is the simplest way to make it work.

Now, let's put it into `Redux`

[adapterActions.js#L448](https://github.com/NordicSemiconductor/pc-nrfconnect-ble/blob/master/lib/actions/adapterActions.js#L448)
```javascript
adapterToUse.on('deviceDiscovered', device => {
    handleDeviceEvent(device, getState, () => {
            dispatch(deviceDiscoveredAction(device));
            dispatch(DiscoveryActions.toggleScan());
    });
});
```

Everything should work fine now! 🥂

**Comment by Nppn7** [comment]
Hi @chunfantasy,

with the following code I could manage to run the scan and stop it without any errors [adapterActions.js#L448](https://github.com/NordicSemiconductor/pc-nrfconnect-ble/blob/master/lib/actions/adapterActions.js#L448):

    adapterToUse.on('deviceDiscovered', device => {
        handleDeviceEvent(device, getState, () => {
            dispatch(deviceDiscoveredAction(device));
            if (device.address === '00:0B:57:15:8C:8F' && device.scanResponse === true) {
                dispatch(DiscoveryActions.toggleScan());
            }
        });
    });

The next step is connecting to the specific device. Here I have several questions: 

What function do I have to call for connecting automatically? Is it `export function connectToDevice(device)` from [adapterActions.js#L1166](https://github.com/NordicSemiconductor/pc-nrfconnect-ble/blob/master/lib/actions/adapterActions.js#L1166)?

And where do I have to call this function? After scan is stopped, at a certain point `function scanStopped(state)` from [discoveryReducer.js#L71](https://github.com/NordicSemiconductor/pc-nrfconnect-ble/blob/master/lib/reducers/discoveryReducer.js#L71) is called. I think connecting from here is wrong and "too early". Also [adapterActions.js](https://github.com/NordicSemiconductor/pc-nrfconnect-ble/blob/master/lib/actions/adapterActions.js) doesn't offer a listener for a stopped scan.

In general I would like to know how `export function connectToDevice(device)` from [adapterActions.js#L1166](https://github.com/NordicSemiconductor/pc-nrfconnect-ble/blob/master/lib/actions/adapterActions.js#L1166) is called when the button is pressed manually, because I can't find the call in the code.

**Comment by chunfantasy** [comment]
Hi @Nppn7 ,

I think what you asked are more like questions than issues.
Therefore, I suggest you to post your questions at [DevZone](https://devzone.nordicsemi.com/questions/)

Have a nice day! 😄  🤞 🍀
