### ISSUE TITLE
Issue when iterating over registry to get COMxx number.

### ISSUE THREAD

**Issue by hakonfam** [NordicSemiconductor/pc-nrfconnect-ble#66]
After performing a reset of the COM port number allocation in windows, nrf connect is not able to correctly map a devices segger serial number to its COM port number.

The log states the following:
`2017-09-11T18:45:57.874Z WARN Multiple J-Link IDs were found in registry for COM58: ["8&24ad048a&0&2","000682452128"]. Using 8&24ad048a&0&2.
2017-09-11T18:45:57.914Z WARN Multiple J-Link IDs were found in registry for COM63: ["7&b5a28a2&0&2","000680474844"]. Using 7&b5a28a2&0&2.`

There are several other devices connected, for which no error message is shown, but these are not being displayed in the UI either (see attached image).

If it is not possible for nrf connect to identify the COM number, it should leave it for the user to specify.
In either case, it should not stop the non-conflicting boards from being displayed.
![nrf_connect_com_port_issue](https://user-images.githubusercontent.com/1547348/30291787-376b4a22-9734-11e7-94b2-c7e6798c8036.PNG)

**Comment by bihanssen** [comment]
Hi, thanks for reporting.
Another observation is that the serial number 7&b5a28a2&0&2 is not even a valid serial and should have been filtered out by the application.

**Comment by mrodem** [comment]
Hi @hakonfam. What approach did you use for resetting the COM port number allocation? Seems that there are multiple ways to do this, e.g. https://superuser.com/questions/408976/how-do-i-clean-up-com-ports-in-use. Trying to reproduce.

**Comment by mrodem** [comment]
We have now implemented a fix for this, which is currently in this pre-release version of nRF Connect: https://github.com/NordicSemiconductor/pc-nrfconnect-core/releases/tag/v2.3.0-alpha.3. It would be great if you could test the pre-release and report back to us.

**Comment by bencefr** [comment]
nRFConnect 2.3.0 has been released with above mentioned fix.
