### ISSUE TITLE
Regularly update advertising payload during scanning

### ISSUE THREAD

**Issue by microbuilder** [NordicSemiconductor/pc-nrfconnect-ble#95]
The RSSI values are constantly updated when scanning, but the ADV packet contents seem to be read once and then cached.

In cases where the adv packet contents are regularly updated, such as Service Data being changed, the changes are not reflected in the UI (see 'ServiceData' below which updates every second with the HW in question here, but I only ever see the initial value read by the PCA10059):

<img width="244" alt="screen shot 2018-07-26 at 21 38 01" src="https://user-images.githubusercontent.com/181073/43284480-337b7dc8-911c-11e8-98f7-48750a3300f4.png">

Would it be possible to update the packet contents at the same time that the RSSI values are updated, to reflect any changes in the ADV packet?

**Comment by bencefr** [comment]
Thank you for reporting, this is a bug that will be added to our backlog.
