### ISSUE TITLE
Multiple characteristics with same UUID only updates first/last instance

### ISSUE THREAD

**Issue by microbuilder** [NordicSemiconductor/pc-nrfconnect-ble#98]
When you have multiple instances of the same characteristic UUID in a service, it seems that only the first and last instances are being updated in the GUI, as shown in the attached gif.

This characteristic supports both read and notify, but enabling notify doesn't lead to any updates either except on the first and last entry.

Manually selecting a middle entry and clicking the 'refresh' icon does update the value.

![screen recording 2018-10-13 at 11 52 47](https://user-images.githubusercontent.com/181073/46904084-2a72de00-cedf-11e8-9911-72146ccc56bf.gif)

**Comment by bihanssen** [comment]
Thanks for reporting, @microbuilder.
Should be fixed with PR #101
